[build]
  functions = "netlify/functions"

[[headers]]
  for = "/admin.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
